version: '3.8'

services:
  pgvector:
    image: ankane/pgvector:latest
    restart: always
    environment:
      POSTGRES_DB: langchain
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ~/volumes/pgvector:/var/lib/postgresql/data
